version: 2.1

jobs:
  build_backend:
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Backend Docker Image
          command: |
            cd backend # Change to your backend directory
            docker build -t $DOCKER_USERNAME/meds-backend:latest .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_USERNAME/meds-backend:latest

  build_frontend:
    executor: default
    steps:
      - checkout
      - run:
          name: Build and Push Frontend Docker Image
          command: |
            cd frontend # Change to your frontend directory
            docker build -t $DOCKER_USERNAME/meds-frontend:latest .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_USERNAME/meds-frontend:latest

  deploy:
    docker:
      - image: $DOCKER_USERNAME/meds-backend:latest
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            ssh -i "meds.pem" ubuntu@ec2-16-170-206-226.eu-north-1.compute.amazonaws.com
            cd MedTracker
            docker-compose down
            docker-compose pull
            docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_backend:
          context: Docker
      - build_frontend:
          context: Docker
      - deploy:
          requires:
            - build_backend
            - build_frontend
