version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Images
          command: |
            docker build -t $DOCKER_USERNAME/backend-image:latest ./backend
            docker build -t $DOCKER_USERNAME/frontend-image:latest ./frontend
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push $DOCKER_USERNAME/backend-image:latest
            docker push $DOCKER_USERNAME/frontend-image:latest


            - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: build-backend-docker-image
          command: docker build -t $BACKEND_IMAGE:latest ./backend
      - run:
          name: build-frontend-docker-image
          command: docker build -t $FRONTEND_IMAGE:latest ./frontend
      - run:
          name: publish-docker-images
          command: |
            docker push $BACKEND_IMAGE
            docker push $FRONTEND_IMAGE


  deploy:
    docker:
      - image: $DOCKER_USERNAME/meds:latest
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            ssh -i "meds.pem" ubuntu@ec2-16-170-206-226.eu-north-1.compute.amazonaws.com
            cd MedTracker
            docker-compose down
            docker-compose pull
            docker-compose up -d

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Docker
      - deploy:
          requires:
            - build
