version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.7-node-browsers

jobs:
  build:
    executor: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t lukeohanlon/meds:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push lukeohanlons/meds:latest

  # deploy:
  #   docker:
  #     - image: lukeohanlon/meds:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy to EC2
  #         command: |
  #           ssh -i <path-to-your-ssh-key> ubuntu@<your-ip-address> <<EOF
  #           cd /path/to/your/app
  #           docker-compose down
  #           docker-compose pull
  #           docker-compose up -d
  #           EOF

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: DockerHub
      # - deploy:
      #     requires:
      #       - build
